version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'java-postgres'
    entrypoint:
      - 'POSTGRES_USER=nfolzordo'
      - 'POSTGRES_PASSWORD=password=YiiT3NiuYVjIt4Y9D0YVm5g80oVOYsKJ'
      - 'POSTGRES_DB = cooking_recipes'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    volumes:
      - ./html:/usr/share/nginx/html

#        https://cooking-recipes-7u6g.onrender.com/
